In [1]:
import numpy as np

# input weights and threshold values 
print('Enter the weights'); 
w1=float(input('Weight w1='))
w2=float(input('Weight w2='))
#print('Enter threshold value');

Enter the weights
Weight w1=1
Weight w2=-1


In [2]:
y=np.array([0, 0, 0, 0])
x1=np.array([0, 0, 1, 1])
x2=np.array([0, 1, 0, 1]) 
t=np.array([0, 1, 1, 1])

In [3]:
net = np.multiply(w1,x1)+np.multiply(w2,x2);
print(net)

[ 0. -1.  1.  0.]


In [4]:
T=float(input('T='))

T=1


In [5]:
for i in range(0,4):
    if net[i] >= T:
        y[i]=1;
    else:
        y[i]=0;

print('Output of net=');
print(y);

Output of net=
[0 0 1 0]


In [6]:
print('Target=');
print(t);

Target=
[0 1 1 1]


In [7]:
if np.array_equal(y,t):
    print('Network has proper weights and threshold values');
    print('Network has worked as AND function');
    print('Output y',y);
    print('Weights of neuron',w1,w2);
    print('Threshold value=',T);
else:
    print('Network has been given WRONG parameters; Run again and provide another set of weights and threshold values');


Network has been given WRONG parameters; Run again and provide another set of weights and threshold values
