In [1]:
import numpy as np

In [2]:
x1 = np.array([0, 0, 1, 1])
x2 = np.array([0, 1, 0, 1])
t = np.array([0, 1, 1, 0])

In [4]:
w11 = float(input('enter w11 value:'))
w21 = float(input('enter w21 value:'))
w12 = float(input('enter w12 value:'))
w22 = float(input('enter w22 value:'))
v1 = float(input('enter v1 value:'))
v2 = float(input('enter v2 value:'))

enter w11 value:1
enter w21 value:-1
enter w12 value:-1
enter w22 value:1
enter v1 value:1
enter v2 value:1


In [5]:
T = float(input('enter Threshold value:'))

enter Threshold value:1


In [6]:
z1 = (w11*x1) + (w21*x2)
print(z1)
Z1 = np.array([0, 0, 0, 0])

[ 0. -1.  1.  0.]


In [7]:
for i in range(0, 4):
    if z1[i] >= T:
        Z1[i] = 1
    else:
        Z1[i] = 0
print(Z1)

[0 0 1 0]


In [8]:
z2 = (w12*x1) + (w22*x2)
print(z2)
Z2 = np.array([0, 0, 0, 0])

[ 0.  1. -1.  0.]


In [9]:
for i in range(0, 4):
    if z2[i] >= T:
        Z2[i] = 1
    else:
        Z2[i] = 0
print(Z2)

[0 1 0 0]


In [10]:
y = (v1*Z1) + (v2*Z2)
print(y)
Y = np.array([0, 0, 0, 0])

[0. 1. 1. 0.]


In [11]:
for i in range(0, 4):
    if y[i] >= T:
        Y[i] = 1
    else:
        Y[i] = 0

print("predicted output:", Y)
print("target output:", t)

predicted output: [0 1 1 0]
target output: [0 1 1 0]


In [12]:
if np.array_equal(Y,t):
    print('Network has proper weights and threshold values');
    print('Network has worked as XOR function');
    print('Output y',Y);
    print('Threshold value=',T);
else:
    print('Network has been given WRONG parameters; Run again and provide another set of weights and threshold values');

Network has proper weights and threshold values
Network has worked as XOR function
Output y [0 1 1 0]
Threshold value= 1.0
